"""
Rich Markdown Response Formatter Service

This service provides professional markdown formatting for various types of responses
including automation reports, multi-step results, file operations, and general content.
"""

import markdown
from jinja2 import Template
from datetime import datetime
from typing import Dict, List, Any, Optional
import structlog
from pathlib import Path

log = structlog.get_logger(__name__)

class ResponseFormatter:
    """Professional markdown formatter with Jinja2 templates"""
    
    def __init__(self):
        self.md = markdown.Markdown(extensions=[
            'tables',
            'fenced_code',
            'codehilite',
            'nl2br',
            'sane_lists',
            'toc',
            'attr_list',
            'def_list',
            'footnotes',
            'md_in_html'
        ])
        
        # Template cache for performance
        self._template_cache = {}
    
    def _get_template(self, template_name: str) -> Template:
        """Get template from cache or load it"""
        if template_name not in self._template_cache:
            template_content = self._load_template(template_name)
            self._template_cache[template_name] = Template(template_content)
        return self._template_cache[template_name]
    
    def _load_template(self, template_name: str) -> str:
        """Load template content based on name"""
        templates = {
            'automation_report': """
# 🤖 Automation Report - {{ date }}

**Status**: {{ status }}  
**Actions Completed**: {{ action_count }}  
**Total Duration**: {{ total_duration }}  
**Success Rate**: {{ success_rate }}%

## 📊 Summary

{% for action in actions %}
### {{ loop.index }}. {{ action.name }}
- **Status**: {{ action.status }}
- **Duration**: {{ action.duration }}
- **Result**: {{ action.result }}
{% if action.details %}
- **Details**: {{ action.details }}
{% endif %}
{% endfor %}

## 🔗 Related Links

{% for link in links %}
- [{{ link.name }}]({{ link.url }})
{% endfor %}

## 📈 Performance Metrics

- **Average Step Duration**: {{ avg_duration }}
- **Total Steps**: {{ total_steps }}
- **Failed Steps**: {{ failed_steps }}

---
*Generated by Synapse AI Assistant at {{ timestamp }}*
""",
            
            'multi_step_result': """
# 🎯 Multi-Step Automation Complete

**Request**: {{ request }}  
**Total Steps**: {{ total_steps }}  
**Success Rate**: {{ success_rate }}%  
**Total Duration**: {{ total_duration }}

{% for step in steps %}
## Step {{ loop.index }}: {{ step.action }}

- **Status**: {{ step.status }}
- **Details**: {{ step.details }}
- **Execution Time**: {{ step.execution_time }}
{% if step.context %}
- **Context**: {{ step.context }}
{% endif %}
{% if step.error %}
- **Error**: {{ step.error }}
{% endif %}

{% endfor %}

## 📋 Context Summary

{% for key, value in context.items() %}
- **{{ key }}**: {{ value }}
{% endfor %}

---
*Multi-step automation completed at {{ timestamp }}*
""",
            
            'file_operation_report': """
# 📁 File Operation Report

**Operation**: {{ operation }}  
**Files Processed**: {{ file_count }}  
**Success Rate**: {{ success_rate }}%  
**Total Size**: {{ total_size }}

## 📊 Operation Summary

{% for file in files %}
### {{ file.name }}
- **Status**: {{ file.status }}
- **Size**: {{ file.size }}
- **Type**: {{ file.type }}
{% if file.error %}
- **Error**: {{ file.error }}
{% endif %}
{% endfor %}

## 📈 Statistics

- **Total Files**: {{ total_files }}
- **Successful**: {{ successful_files }}
- **Failed**: {{ failed_files }}
- **Total Size**: {{ total_size_human }}

---
*File operation completed at {{ timestamp }}*
""",
            
            'google_drive_report': """
# ☁️ Google Drive Operation Report

**Operation**: {{ operation }}  
**Files Processed**: {{ file_count }}  
**Success Rate**: {{ success_rate }}%

## 📊 Drive Operations

{% for file in files %}
### {{ file.name }}
- **Status**: {{ file.status }}
- **Drive ID**: {{ file.drive_id }}
- **Size**: {{ file.size }}
- **MIME Type**: {{ file.mime_type }}
{% if file.url %}
- **URL**: [Open in Drive]({{ file.url }})
{% endif %}
{% if file.error %}
- **Error**: {{ file.error }}
{% endif %}
{% endfor %}

## 🔗 Drive Links

{% for link in drive_links %}
- [{{ link.name }}]({{ link.url }})
{% endfor %}

---
*Google Drive operation completed at {{ timestamp }}*
""",
            
            'google_sheets_report': """
# 📊 Google Sheets Operation Report

**Operation**: {{ operation }}  
**Spreadsheets Processed**: {{ sheet_count }}  
**Success Rate**: {{ success_rate }}%

## 📈 Sheets Operations

{% for sheet in sheets %}
### {{ sheet.name }}
- **Status**: {{ sheet.status }}
- **Sheet ID**: {{ sheet.sheet_id }}
- **URL**: [Open in Sheets]({{ sheet.url }})
{% if sheet.worksheet %}
- **Worksheet**: {{ sheet.worksheet }}
{% endif %}
{% if sheet.rows_affected %}
- **Rows Affected**: {{ sheet.rows_affected }}
{% endif %}
{% if sheet.error %}
- **Error**: {{ sheet.error }}
{% endif %}
{% endfor %}

## 🔗 Sheet Links

{% for link in sheet_links %}
- [{{ link.name }}]({{ link.url }})
{% endfor %}

---
*Google Sheets operation completed at {{ timestamp }}*
""",
            
            'terminal_report': """
# 💻 Terminal Command Report

**Command**: `{{ command }}`  
**Status**: {{ status }}  
**Exit Code**: {{ exit_code }}  
**Duration**: {{ duration }}

## 📋 Output

```bash
{{ output }}
```

{% if error %}
## ❌ Error Output

```bash
{{ error }}
```
{% endif %}

## 📊 Command Details

- **Working Directory**: {{ working_dir }}
- **User**: {{ user }}
- **Timestamp**: {{ timestamp }}

---
*Terminal command executed at {{ timestamp }}*
""",
            
            'schedule_report': """
# ⏰ Schedule Operation Report

**Operation**: {{ operation }}  
**Tasks Processed**: {{ task_count }}  
**Success Rate**: {{ success_rate }}%

## 📅 Scheduled Tasks

{% for task in tasks %}
### {{ task.name }}
- **Status**: {{ task.status }}
- **Schedule**: {{ task.schedule }}
- **Next Run**: {{ task.next_run }}
- **Task Type**: {{ task.task_type }}
{% if task.error %}
- **Error**: {{ task.error }}
{% endif %}
{% endfor %}

## 📈 Schedule Statistics

- **Total Tasks**: {{ total_tasks }}
- **Active Tasks**: {{ active_tasks }}
- **Paused Tasks**: {{ paused_tasks }}
- **Failed Tasks**: {{ failed_tasks }}

---
*Schedule operation completed at {{ timestamp }}*
""",
            
            'retrieve_info': """
{{ content }}
""",
            
            'store_info': """
✅ {{ content }}
""",
            
            'browser_automation': """
🤖 **{{ action|title }}**: {{ content }}

{% if screenshot_url %}
![Automation Screenshot]({{ screenshot_url }})
{% endif %}

{% if details %}
**Details**: {{ details }}
{% endif %}
""",
            
            'weather': """
🌤️ **Weather in {{ location }}**

**Temperature**: {{ temperature }}  
**Condition**: {{ description }}

{% if additional_info %}
{{ additional_info }}
{% endif %}
""",
            
            'web_search': """
{{ content }}

{% if links %}
{% for link in links %}
- [{{ link.title }}]({{ link.url }})
{% endfor %}
{% endif %}
""",
            
            'news': """
📰 {{ content }}

{% if links %}
{% for link in links %}
- [{{ link.title }}]({{ link.url }})
{% endfor %}
{% endif %}
""",
            
            'general_response': """
{{ content }}
"""
        }
        
        return templates.get(template_name, templates['general_response'])
    
    def format_automation_report(self, data: Dict[str, Any]) -> str:
        """Format automation report with rich markdown"""
        template = self._get_template('automation_report')
        
        # Calculate metrics
        actions = data.get('actions', [])
        total_actions = len(actions)
        successful_actions = len([a for a in actions if a.get('status') == 'success'])
        success_rate = (successful_actions / total_actions * 100) if total_actions > 0 else 0
        
        # Calculate durations
        total_duration = sum(float(a.get('duration', 0)) for a in actions)
        avg_duration = total_duration / total_actions if total_actions > 0 else 0
        
        context = {
            'date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'timestamp': datetime.now().isoformat(),
            'status': data.get('status', 'completed'),
            'action_count': total_actions,
            'total_duration': f"{total_duration:.2f}s",
            'success_rate': f"{success_rate:.1f}",
            'actions': actions,
            'links': data.get('links', []),
            'avg_duration': f"{avg_duration:.2f}s",
            'total_steps': total_actions,
            'failed_steps': total_actions - successful_actions
        }
        
        return template.render(**context)
    
    def format_multi_step_result(self, data: Dict[str, Any]) -> str:
        """Format multi-step automation result"""
        template = self._get_template('multi_step_result')
        
        steps = data.get('steps_executed', [])
        total_steps = len(steps)
        successful_steps = len([s for s in steps if s.get('status') == 'success'])
        success_rate = (successful_steps / total_steps * 100) if total_steps > 0 else 0
        
        # Calculate total duration
        total_duration = sum(float(s.get('execution_time', 0)) for s in steps)
        
        context = {
            'request': data.get('user_request', 'Multi-step automation'),
            'total_steps': total_steps,
            'success_rate': f"{success_rate:.1f}",
            'total_duration': f"{total_duration:.2f}s",
            'steps': steps,
            'context': data.get('context', {}),
            'timestamp': datetime.now().isoformat()
        }
        
        return template.render(**context)
    
    def format_file_operation_report(self, data: Dict[str, Any]) -> str:
        """Format file operation report"""
        template = self._get_template('file_operation_report')
        
        files = data.get('files', [])
        total_files = len(files)
        successful_files = len([f for f in files if f.get('status') == 'success'])
        success_rate = (successful_files / total_files * 100) if total_files > 0 else 0
        
        # Calculate total size
        total_size = sum(int(f.get('size', 0)) for f in files)
        total_size_human = self._format_bytes(total_size)
        
        context = {
            'operation': data.get('operation', 'File operation'),
            'file_count': total_files,
            'success_rate': f"{success_rate:.1f}",
            'total_size': total_size_human,
            'files': files,
            'total_files': total_files,
            'successful_files': successful_files,
            'failed_files': total_files - successful_files,
            'total_size_human': total_size_human,
            'timestamp': datetime.now().isoformat()
        }
        
        return template.render(**context)
    
    def format_google_drive_report(self, data: Dict[str, Any]) -> str:
        """Format Google Drive operation report"""
        template = self._get_template('google_drive_report')
        
        files = data.get('files', [])
        total_files = len(files)
        successful_files = len([f for f in files if f.get('status') == 'success'])
        success_rate = (successful_files / total_files * 100) if total_files > 0 else 0
        
        context = {
            'operation': data.get('operation', 'Google Drive operation'),
            'file_count': total_files,
            'success_rate': f"{success_rate:.1f}",
            'files': files,
            'drive_links': data.get('drive_links', []),
            'timestamp': datetime.now().isoformat()
        }
        
        return template.render(**context)
    
    def format_google_sheets_report(self, data: Dict[str, Any]) -> str:
        """Format Google Sheets operation report"""
        template = self._get_template('google_sheets_report')
        
        sheets = data.get('sheets', [])
        total_sheets = len(sheets)
        successful_sheets = len([s for s in sheets if s.get('status') == 'success'])
        success_rate = (successful_sheets / total_sheets * 100) if total_sheets > 0 else 0
        
        context = {
            'operation': data.get('operation', 'Google Sheets operation'),
            'sheet_count': total_sheets,
            'success_rate': f"{success_rate:.1f}",
            'sheets': sheets,
            'sheet_links': data.get('sheet_links', []),
            'timestamp': datetime.now().isoformat()
        }
        
        return template.render(**context)
    
    def format_terminal_report(self, data: Dict[str, Any]) -> str:
        """Format terminal command report"""
        template = self._get_template('terminal_report')
        
        context = {
            'command': data.get('command', ''),
            'status': data.get('status', 'completed'),
            'exit_code': data.get('exit_code', 0),
            'duration': data.get('duration', '0.00s'),
            'output': data.get('output', ''),
            'error': data.get('error', ''),
            'working_dir': data.get('working_dir', '/'),
            'user': data.get('user', 'system'),
            'timestamp': datetime.now().isoformat()
        }
        
        return template.render(**context)
    
    def format_schedule_report(self, data: Dict[str, Any]) -> str:
        """Format schedule operation report"""
        template = self._get_template('schedule_report')
        
        tasks = data.get('tasks', [])
        total_tasks = len(tasks)
        successful_tasks = len([t for t in tasks if t.get('status') == 'success'])
        success_rate = (successful_tasks / total_tasks * 100) if total_tasks > 0 else 0
        
        context = {
            'operation': data.get('operation', 'Schedule operation'),
            'task_count': total_tasks,
            'success_rate': f"{success_rate:.1f}",
            'tasks': tasks,
            'total_tasks': total_tasks,
            'active_tasks': len([t for t in tasks if t.get('status') == 'active']),
            'paused_tasks': len([t for t in tasks if t.get('status') == 'paused']),
            'failed_tasks': total_tasks - successful_tasks,
            'timestamp': datetime.now().isoformat()
        }
        
        return template.render(**context)
    
    def format_general_response(self, data: Dict[str, Any]) -> str:
        """Format general response with markdown"""
        template = self._get_template('general_response')
        
        context = {
            'title': data.get('title', 'Response'),
            'content': data.get('content', ''),
            'details': data.get('details', ''),
            'links': data.get('links', []),
            'metadata': data.get('metadata', {}),
            'timestamp': datetime.now().isoformat()
        }
        
        return template.render(**context)
    
    def to_html(self, markdown_text: str) -> str:
        """Convert markdown to HTML with syntax highlighting"""
        try:
            html = self.md.convert(markdown_text)
            # Reset markdown instance for next use
            self.md.reset()
            return html
        except Exception as e:
            log.error("Failed to convert markdown to HTML", error=str(e))
            return f"<p>Error converting markdown: {str(e)}</p>"
    
    def _format_simple_template(self, template_name: str, data: Dict[str, Any]) -> str:
        """Format using simple templates"""
        template = self._get_template(template_name)
        
        # Add timestamp for consistency
        data['timestamp'] = datetime.now().isoformat()
        
        return template.render(**data)
    
    def _format_bytes(self, bytes_value: int) -> str:
        """Format bytes to human readable format"""
        for unit in ['B', 'KB', 'MB', 'GB', 'TB']:
            if bytes_value < 1024.0:
                return f"{bytes_value:.1f} {unit}"
            bytes_value /= 1024.0
        return f"{bytes_value:.1f} PB"
    
    def format_response(self, content: Any, response_type: str = 'general', metadata: Optional[Dict[str, Any]] = None) -> Dict[str, str]:
        """
        Main formatting method that returns both markdown and HTML
        
        Args:
            content: The content to format
            response_type: Type of response (automation_report, multi_step_result, etc.)
            metadata: Additional metadata for formatting
            
        Returns:
            Dict with 'markdown', 'html', and 'raw' keys
        """
        try:
            # Prepare data
            if isinstance(content, dict):
                data = content
            else:
                data = {'content': str(content)}
            
            if metadata:
                data.update(metadata)
            
            # Format based on type
            if response_type == 'retrieve_info':
                markdown_content = self._format_simple_template('retrieve_info', data)
            elif response_type == 'store_info':
                markdown_content = self._format_simple_template('store_info', data)
            elif response_type == 'browser_automation':
                markdown_content = self._format_simple_template('browser_automation', data)
            elif response_type == 'weather':
                markdown_content = self._format_simple_template('weather', data)
            elif response_type == 'web_search':
                markdown_content = self._format_simple_template('web_search', data)
            elif response_type == 'news':
                markdown_content = self._format_simple_template('news', data)
            elif response_type == 'automation_report':
                markdown_content = self.format_automation_report(data)
            elif response_type == 'multi_step_result':
                markdown_content = self.format_multi_step_result(data)
            elif response_type == 'file_operation':
                markdown_content = self.format_file_operation_report(data)
            elif response_type == 'google_drive':
                markdown_content = self.format_google_drive_report(data)
            elif response_type == 'google_sheets':
                markdown_content = self.format_google_sheets_report(data)
            elif response_type == 'terminal':
                markdown_content = self.format_terminal_report(data)
            elif response_type == 'schedule':
                markdown_content = self.format_schedule_report(data)
            else:
                markdown_content = self._format_simple_template('general_response', data)
            
            # Convert to HTML
            html_content = self.to_html(markdown_content)
            
            return {
                "markdown": markdown_content,
                "html": html_content,
                "raw": str(content)
            }
            
        except Exception as e:
            log.error("Failed to format response", error=str(e), response_type=response_type)
            return {
                "markdown": f"Error formatting response: {str(e)}",
                "html": f"<p>Error formatting response: {str(e)}</p>",
                "raw": str(content)
            }

