"""Add is_public and share_uuid to conversations

Revision ID: 2ae56a7ee215
Revises: d57cb324c744
Create Date: 2025-09-23 17:52:08.143214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ae56a7ee215'
down_revision: Union[str, Sequence[str], None] = 'd57cb324c744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.add_column('conversations', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('conversations', sa.Column('share_uuid', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_conversations_is_public'), 'conversations', ['is_public'], unique=False)
    op.create_index(op.f('ix_conversations_share_uuid'), 'conversations', ['share_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_share_uuid'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_is_public'), table_name='conversations')
    op.drop_column('conversations', 'share_uuid')
    op.drop_column('conversations', 'is_public')
    op.create_table('messages',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('extra_meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.uuid'], name=op.f('messages_conversation_id_fkey')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('messages_pkey'))
    )
    # ### end Alembic commands ###
