"""Add google_access_token and token_expires_at columns to users

Revision ID: 9fe618a65ed3
Revises: f00aa8e36364
Create Date: 2025-10-09 13:36:31.433728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe618a65ed3'
down_revision: Union[str, Sequence[str], None] = 'f00aa8e36364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_token_expires_at')
    op.drop_column('users', 'google_access_token')
    # ### end Alembic commands ###