"""Add hashed_password column to users

Revision ID: ac6c1c8d3909
Revises: 8d3c625b84f5
Create Date: 2025-09-01 06:52:13.933754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac6c1c8d3909'
down_revision: Union[str, Sequence[str], None] = '8d3c625b84f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_provider_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.create_index(op.f('ix_users_google_provider_id'), 'users', ['google_provider_id'], unique=True)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_google_provider_id'), table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'google_provider_id')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
